#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Quicky\Console\StartCommand;

$application = new Application("QuickyPHP - CLI");

$application->add(new StartCommand());

$application->run();